.TH "BTM.c" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BTM.c \- Implementation of Time Base 0 and Time Base 1 timers initialization\&. This file provides the definition for initializing the Time Base timers, configuring their clock source, enabling or disabling the timers, setting time-out periods, and enabling global interrupts\&. Author: Mohamad Khosravi https://github.com/Mohamadkhosravi Date: 2024\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'BTM\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTimerBaseInit\fP (void)"
.br
.RI "Initializes the Time Base 0 & 1 timers\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implementation of Time Base 0 and Time Base 1 timers initialization\&. This file provides the definition for initializing the Time Base timers, configuring their clock source, enabling or disabling the timers, setting time-out periods, and enabling global interrupts\&. Author: Mohamad Khosravi https://github.com/Mohamadkhosravi Date: 2024\&. 


.SH "Function Documentation"
.PP 
.SS "void TimerBaseInit (void )"

.PP
Initializes the Time Base 0 & 1 timers\&. Initializes Time Base 0 & 1 timers\&.

.PP
This function configures the prescaler clock source for the timers, enables or disables the Time Base 0 and Time Base 1 timers based on pre-defined macros, sets their time-out periods, and enables global interrupts to allow the timers to trigger interrupt service routines\&.

.PP
\fBNote\fP
.RS 4
This function should be called before using the Time Base timers to ensure proper configuration and operation\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
