.TH "PTM.c" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PTM.c \- Implementation file for the PTM (Pulse Timer Module) for Holtek MCUs\&. This file contains the definitions of functions for initializing and using the PTM in embedded applications\&. Author: Mohamad Khosravi https://github.com/Mohamadkhosravi Date: 2024\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <PTM\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPTimerInit\fP (void)"
.br
.RI "Initializes the Pulse Timer Module (PTM)\&. "
.ti -1c
.RI "void \fBPWMSeter\fP (char status)"
.br
.RI "Sets the PWM status\&. "
.ti -1c
.RI "unsigned int \fBreadPTimer\fP (void)"
.br
.RI "Reads the current value of the Pulse Timer Module (PTM)\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implementation file for the PTM (Pulse Timer Module) for Holtek MCUs\&. This file contains the definitions of functions for initializing and using the PTM in embedded applications\&. Author: Mohamad Khosravi https://github.com/Mohamadkhosravi Date: 2024\&. 


.SH "Function Documentation"
.PP 
.SS "void PTimerInit (void )"

.PP
Initializes the Pulse Timer Module (PTM)\&. Function declarations\&.

.PP
This function configures the PTM's clock, mode, output settings, and initializes the necessary registers\&.

.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.SS "void PWMSeter (char status)"

.PP
Sets the PWM status\&. Sets the PWM status (active or inactive)

.PP
This function configures the PWM output state based on the provided status\&.

.PP
\fBParameters\fP
.RS 4
\fIstatus\fP The status to set for the PWM (1 for active, 0 for inactive)\&. 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.SS "unsigned int readPTimer (void )"

.PP
Reads the current value of the Pulse Timer Module (PTM)\&. Reads the current value of the PTM timer\&.

.PP
This function retrieves the current timer value from the PTM\&.

.PP
\fBReturns\fP
.RS 4
The current timer value as an unsigned integer\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
