.TH "PTM.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PTM.h \- Header file for the Periodic Timer Module (PTM) for Holtek MCUs\&. This file defines the macros and function prototypes for the PTM, which is used for generating timing signals, PWM, and input capture functionalities\&. Author: Mohamad Khosravi https://github.com/Mohamadkhosravi Date: 2024\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <Main\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPT_SYS_DIVIDE_4\fP   0"
.br
.RI "PTM Counter Clock Selection This section defines the clock sources for the PTM counter\&. "
.ti -1c
.RI "#define \fBPT_SYS\fP   1"
.br
.ti -1c
.RI "#define \fBPT_H_DIVIDE_16\fP   2"
.br
.ti -1c
.RI "#define \fBPT_H_DIVIDE_64\fP   3"
.br
.ti -1c
.RI "#define \fBPT_SUB1\fP   4"
.br
.ti -1c
.RI "#define \fBPT_SUB2\fP   5"
.br
.ti -1c
.RI "#define \fBPT_STCK_RISING\fP   6"
.br
.ti -1c
.RI "#define \fBPT_STCK_FALLING\fP   7"
.br
.ti -1c
.RI "#define \fBPTIMER_CLOCK\fP   PT_SYS"
.br
.ti -1c
.RI "#define \fBPTM_COMPARE_MATCH_OUTPUT_MODE\fP   0"
.br
.RI "PTM Operating Modes This section defines the operating modes for the PTM\&. "
.ti -1c
.RI "#define \fBPTM_CAPTURE_INPUT_MODE\fP   1"
.br
.ti -1c
.RI "#define \fBPTM_PWM_OR_SINGLE_PULSE_OUTPUT_MODE\fP   2"
.br
.ti -1c
.RI "#define \fBPTM_TIMER_COUNTER_MODE\fP   3"
.br
.ti -1c
.RI "#define \fBPTM_MODE\fP   PTM_CAPTURE_INPUT_MODE"
.br
.ti -1c
.RI "#define \fBPTM_NO_CHANGE\fP   0"
.br
.RI "PTM External Pins Function This section defines the functions of external pins for the PTM\&. "
.ti -1c
.RI "#define \fBPTM_OUTPUT_LOW\fP   1"
.br
.ti -1c
.RI "#define \fBPTM_OUTPUT_HIGH\fP   2"
.br
.ti -1c
.RI "#define \fBPTM_TOGGLE_OUTPUT\fP   3"
.br
.ti -1c
.RI "#define \fBPTM_PWM_INACTIVE\fP   0"
.br
.ti -1c
.RI "#define \fBPTM_PWM_ACTIVE\fP   1"
.br
.ti -1c
.RI "#define \fBPTM_PWM_OUTPUT\fP   2"
.br
.ti -1c
.RI "#define \fBPTM_SINGLE_PULSE_OUTPUT\fP   3"
.br
.ti -1c
.RI "#define \fBPTM_PIN_FUNCTION\fP   \fBPTM_NO_CHANGE\fP"
.br
.ti -1c
.RI "#define \fBPTM_INITIAL_LOW\fP   0"
.br
.RI "PTM Output Mode This section defines the output mode of the PTM\&. "
.ti -1c
.RI "#define \fBPTM_INITIAL_HIGH\fP   1"
.br
.ti -1c
.RI "#define \fBPTM_ACTIVE_LOW\fP   0"
.br
.ti -1c
.RI "#define \fBPTM_ACTIVE_HIGH\fP   1"
.br
.ti -1c
.RI "#define \fBPTM_OUTPUT_MODE\fP   \fBPTM_INITIAL_LOW\fP"
.br
.ti -1c
.RI "#define \fBPTM_COUNTER_OFF\fP   0"
.br
.RI "PTM Counter On/Off Control This section defines the control for turning the PTM counter on or off\&. "
.ti -1c
.RI "#define \fBPTM_COUNTER_ON\fP   1"
.br
.ti -1c
.RI "#define \fBPTM_COUNTER\fP   PTM_COUNTER_ON"
.br
.ti -1c
.RI "#define \fBPTM_NON_INVERT\fP   0"
.br
.RI "PTM Output Polarity This section defines the output polarity of the PTM\&. "
.ti -1c
.RI "#define \fBPTM_INVERT\fP   1"
.br
.ti -1c
.RI "#define \fBPTM_OUTPUT_POLARITY\fP   \fBPTM_NON_INVERT\fP"
.br
.ti -1c
.RI "#define \fBPTM_PTPI_INPUT\fP   0"
.br
.RI "PTM Capture Trigger Source Selection This section defines the trigger sources for capturing input signals\&. "
.ti -1c
.RI "#define \fBPTM_PTCK_INPUT\fP   1"
.br
.ti -1c
.RI "#define \fBPTM_CAPTURE_TRIGGER\fP   \fBPTM_PTPI_INPUT\fP"
.br
.ti -1c
.RI "#define \fBPTM_COMPARE_MATCH_P\fP   0"
.br
.RI "PTM Comparator Clear Condition Selection This section defines conditions for clearing the PTM comparator\&. "
.ti -1c
.RI "#define \fBPTM_COMPARE_MATCH_A\fP   1"
.br
.ti -1c
.RI "#define \fBPTM_SELECT_CLEAR_COMPARE_MATCH\fP   \fBPTM_COMPARE_MATCH_P\fP"
.br
.ti -1c
.RI "#define \fBPTM_COMPARE_P_MATCH\fP   0"
.br
.RI "Select PTM Counter clear condition in capture input mode This section defines clear conditions when in capture input mode\&. "
.ti -1c
.RI "#define \fBPTM_COMPARE_P_MATCH_OR_PTCK_PTPI_RISING_EDGE\fP   1"
.br
.ti -1c
.RI "#define \fBPTM_COMPARE_P_MATCH_OR_PTCK_PTPI_FALING_EDGE\fP   2"
.br
.ti -1c
.RI "#define \fBPTM_COMPARE_P_MATCH_OR_PTCK_PTPI_DUAL_EDGE\fP   3"
.br
.ti -1c
.RI "#define \fBPTM_SELECT_CLEAR_CONDITION_IN_CAPTURE_INPUT\fP   PTM_COMPARE_P_MATCH_OR_PTCK_PTPI_RISING_EDGE"
.br
.ti -1c
.RI "#define \fBFALLING_EDGE_TRIAGE_COUNTER_LATCH\fP   0"
.br
.RI "PTM counter value latch edge flag This section defines the edge flag for latching counter values\&. "
.ti -1c
.RI "#define \fBRISING_EDGE_TRIAGE_COUNTER_LATCH\fP   1"
.br
.ti -1c
.RI "#define \fBCOUNTER_VALUE_LATCH_EDGE\fP   \fBFALLING_EDGE_TRIAGE_COUNTER_LATCH\fP"
.br
.ti -1c
.RI "#define \fBPTM_CCRA_LOW_BYTE_MASK\fP   0x01"
.br
.RI "PTM CCRA Low & High Byte Mask This section defines masks for low and high bytes of the PTM CCRA\&. "
.ti -1c
.RI "#define \fBPTM_CCRA_HIGH_BYTE_MASK\fP   0"
.br
.ti -1c
.RI "#define \fBPTM_CCRB_LOW_BYTE_MASK\fP   0x01"
.br
.ti -1c
.RI "#define \fBPTM_CCRB_HIGH_BYTE_MASK\fP   0"
.br
.ti -1c
.RI "#define \fBPTM_CCRP_LOW_BYTE_MASK\fP   0x01"
.br
.ti -1c
.RI "#define \fBPTM_CCRP_HIGH_BYTE_MASK\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPTimerInit\fP (void)"
.br
.RI "Function declarations\&. "
.ti -1c
.RI "void \fBPWMSeter\fP (char status)"
.br
.RI "Sets the PWM status (active or inactive) "
.ti -1c
.RI "unsigned int \fBreadPTimer\fP (void)"
.br
.RI "Reads the current value of the PTM timer\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for the Periodic Timer Module (PTM) for Holtek MCUs\&. This file defines the macros and function prototypes for the PTM, which is used for generating timing signals, PWM, and input capture functionalities\&. Author: Mohamad Khosravi https://github.com/Mohamadkhosravi Date: 2024\&. 


.SH "Function Documentation"
.PP 
.SS "void PTimerInit (void )"

.PP
Function declarations\&. The following functions are declared for initializing and using the PTM\&.

.PP
Initializes the PTM

.PP
Function declarations\&.

.PP
This function configures the PTM's clock, mode, output settings, and initializes the necessary registers\&.

.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.SS "void PWMSeter (char status)"

.PP
Sets the PWM status (active or inactive) Sets the PWM status (active or inactive)

.PP
This function configures the PWM output state based on the provided status\&.

.PP
\fBParameters\fP
.RS 4
\fIstatus\fP The status to set for the PWM (1 for active, 0 for inactive)\&. 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.SS "unsigned int readPTimer (void )"

.PP
Reads the current value of the PTM timer\&. Reads the current value of the PTM timer\&.

.PP
This function retrieves the current timer value from the PTM\&.

.PP
\fBReturns\fP
.RS 4
The current timer value as an unsigned integer\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
