.TH "STM.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STM.h
.SH SYNOPSIS
.br
.PP
\fR#include <Main\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBST_FSYS_DIVIDE_4\fP   0"
.br
.RI "STM Counter Clock Selection This section defines the clock sources for the STM counter\&. "
.ti -1c
.RI "#define \fBST_FSYS\fP   1"
.br
.ti -1c
.RI "#define \fBST_FH_DIVIDE_16\fP   2"
.br
.ti -1c
.RI "#define \fBST_FH_DIVIDE_64\fP   3"
.br
.ti -1c
.RI "#define \fBST_FSUB1\fP   4"
.br
.ti -1c
.RI "#define \fBST_FSUB2\fP   5"
.br
.ti -1c
.RI "#define \fBST_STCK_RISING\fP   6"
.br
.ti -1c
.RI "#define \fBST_STCK_FALLING\fP   7"
.br
.ti -1c
.RI "#define \fBSTIMER_CLOCK\fP   \fBST_FSYS\fP"
.br
.ti -1c
.RI "#define \fBSTM_1024_CLOCKS\fP   0"
.br
.RI "STM Comparator P Match Period This section defines the various comparator match periods for the STM\&. "
.ti -1c
.RI "#define \fBSTM_128_CLOCKS\fP   1"
.br
.ti -1c
.RI "#define \fBSTM_256_CLOCKS\fP   2"
.br
.ti -1c
.RI "#define \fBSTM_384_CLOCKS\fP   3"
.br
.ti -1c
.RI "#define \fBSTM_512_CLOCKS\fP   4"
.br
.ti -1c
.RI "#define \fBSTM_640_CLOCKS\fP   5"
.br
.ti -1c
.RI "#define \fBSTM_768_CLOCKS\fP   6"
.br
.ti -1c
.RI "#define \fBSTM_896_CLOCKS\fP   7"
.br
.ti -1c
.RI "#define \fBSTM_PERIOD\fP   \fBSTM_1024_CLOCKS\fP"
.br
.ti -1c
.RI "#define \fBSTM_COMPARE_MATCH_OUTPUT_MODE\fP   0"
.br
.RI "STM Operating Modes This section defines the operating modes for the STM\&. "
.ti -1c
.RI "#define \fBSTM_TIMER_COUNTER_MODE\fP   1"
.br
.ti -1c
.RI "#define \fBSTM_CAPTURE_INPUT_MODE\fP   2"
.br
.ti -1c
.RI "#define \fBSTM_PWM_OUTPUT_MODE\fP   3"
.br
.ti -1c
.RI "#define \fBSTM_SINGLE_PULSE_OUTPUT_MODE\fP   4"
.br
.ti -1c
.RI "#define \fBSTM_MODE\fP   \fBSTM_COMPARE_MATCH_OUTPUT_MODE\fP"
.br
.ti -1c
.RI "#define \fBNO_CHANGE\fP   0"
.br
.RI "STM External Pins Function This section defines the functions of external pins for the STM\&. "
.ti -1c
.RI "#define \fBOUTPUT_LOW\fP   1"
.br
.ti -1c
.RI "#define \fBOUTPUT_HIGH\fP   2"
.br
.ti -1c
.RI "#define \fBTOGGLE_OUTPUT\fP   3"
.br
.ti -1c
.RI "#define \fBPWM_OUTPUT_INACTIVE_STATE\fP   0"
.br
.ti -1c
.RI "#define \fBPWM_OUTPUT_ACTIVE_STATE\fP   1"
.br
.ti -1c
.RI "#define \fBPWM_OUTPUT\fP   2"
.br
.ti -1c
.RI "#define \fBSINGLE_PULSE_ACTIVE_STATE\fP   3"
.br
.ti -1c
.RI "#define \fBINPUT_CAPTURE_AT_RISING_EDGE\fP   0"
.br
.ti -1c
.RI "#define \fBINPUT_CAPTURE_AT_FULLING_EDGE\fP   1"
.br
.ti -1c
.RI "#define \fBINPUT_CAPTURE_BOTH_RISING_FULLING_EDGE\fP   2"
.br
.ti -1c
.RI "#define \fBINPUT_CAPTURE_DISABLE\fP   3"
.br
.ti -1c
.RI "#define \fBSTM_PIN_FUNCTION\fP   \fBNO_CHANGE\fP"
.br
.ti -1c
.RI "#define \fBINITIAL_LOW\fP   0"
.br
.RI "STM Output Mode This section defines the output mode of the STM\&. "
.ti -1c
.RI "#define \fBINITIAL_HIGH\fP   1"
.br
.ti -1c
.RI "#define \fBACTIVE_LOW\fP   0"
.br
.ti -1c
.RI "#define \fBACTIVE_HIGH\fP   1"
.br
.ti -1c
.RI "#define \fBSTM_OUTPUT_MODE\fP   \fBINITIAL_LOW\fP"
.br
.ti -1c
.RI "#define \fBSTM_COUNTER_OFF\fP   0"
.br
.RI "STM Counter On/Off Control This section defines the control for turning the STM counter on or off\&. "
.ti -1c
.RI "#define \fBSTM_COUNTER_ON\fP   1"
.br
.ti -1c
.RI "#define \fBSTM_COUNTER\fP   \fBSTM_COUNTER_ON\fP"
.br
.ti -1c
.RI "#define \fBSTM_NON_INVERT\fP   0"
.br
.RI "STM Output Polarity This section defines the output polarity of the STM\&. "
.ti -1c
.RI "#define \fBSTM_INVERT\fP   1"
.br
.ti -1c
.RI "#define \fBSTM_OUTPUT_POLARITY\fP   \fBSTM_NON_INVERT\fP"
.br
.ti -1c
.RI "#define \fBSTM_DUTY\fP   1"
.br
.RI "STM PWM Duty/Period Control This section defines the duty and period control for the PWM\&. "
.ti -1c
.RI "#define \fBSTM_PERIOD\fP   0"
.br
.ti -1c
.RI "#define \fBSTM_PWM_DUTY\fP   \fBSTM_DUTY\fP"
.br
.ti -1c
.RI "#define \fBSTM_COMPARE_MATCH_P\fP   0"
.br
.RI "STM Comparator Clear Condition Selection This section defines the conditions for clearing the STM comparator\&. "
.ti -1c
.RI "#define \fBSTM_COMPARE_MATCH_A\fP   1"
.br
.ti -1c
.RI "#define \fBSTM_SELECT_CLEAR_COMPARE_MATCH\fP   \fBSTM_COMPARE_MATCH_A\fP"
.br
.ti -1c
.RI "#define \fBSTM_CCRA_LOW_BYTE_MASK\fP   0x01"
.br
.RI "STM CCRA Low Byte Mask This section defines masks for low and high bytes of the STM CCRA\&. "
.ti -1c
.RI "#define \fBSTM_CCRA_HIGH_BYTE_MASK\fP   0x0"
.br
.RI "STM CCRA High Byte Mask This section defines masks for low and high bytes of the STM CCRA\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSTimerInit\fP (void)"
.br
.RI "Function declarations\&. "
.ti -1c
.RI "unsigned int \fBreadSTimer\fP (void)"
.br
.RI "Reads the current value of the STM timer\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ACTIVE_HIGH   1"

.SS "#define ACTIVE_LOW   0"

.SS "#define INITIAL_HIGH   1"

.SS "#define INITIAL_LOW   0"

.PP
STM Output Mode This section defines the output mode of the STM\&. 
.SS "#define INPUT_CAPTURE_AT_FULLING_EDGE   1"

.SS "#define INPUT_CAPTURE_AT_RISING_EDGE   0"

.SS "#define INPUT_CAPTURE_BOTH_RISING_FULLING_EDGE   2"

.SS "#define INPUT_CAPTURE_DISABLE   3"

.SS "#define NO_CHANGE   0"

.PP
STM External Pins Function This section defines the functions of external pins for the STM\&. 
.SS "#define OUTPUT_HIGH   2"

.SS "#define OUTPUT_LOW   1"

.SS "#define PWM_OUTPUT   2"

.SS "#define PWM_OUTPUT_ACTIVE_STATE   1"

.SS "#define PWM_OUTPUT_INACTIVE_STATE   0"

.SS "#define SINGLE_PULSE_ACTIVE_STATE   3"

.SS "#define ST_FH_DIVIDE_16   2"

.SS "#define ST_FH_DIVIDE_64   3"

.SS "#define ST_FSUB1   4"

.SS "#define ST_FSUB2   5"

.SS "#define ST_FSYS   1"

.SS "#define ST_FSYS_DIVIDE_4   0"

.PP
STM Counter Clock Selection This section defines the clock sources for the STM counter\&. 
.SS "#define ST_STCK_FALLING   7"

.SS "#define ST_STCK_RISING   6"

.SS "#define STIMER_CLOCK   \fBST_FSYS\fP"

.SS "#define STM_1024_CLOCKS   0"

.PP
STM Comparator P Match Period This section defines the various comparator match periods for the STM\&. 
.SS "#define STM_128_CLOCKS   1"

.SS "#define STM_256_CLOCKS   2"

.SS "#define STM_384_CLOCKS   3"

.SS "#define STM_512_CLOCKS   4"

.SS "#define STM_640_CLOCKS   5"

.SS "#define STM_768_CLOCKS   6"

.SS "#define STM_896_CLOCKS   7"

.SS "#define STM_CAPTURE_INPUT_MODE   2"

.SS "#define STM_CCRA_HIGH_BYTE_MASK   0x0"

.PP
STM CCRA High Byte Mask This section defines masks for low and high bytes of the STM CCRA\&. 
.SS "#define STM_CCRA_LOW_BYTE_MASK   0x01"

.PP
STM CCRA Low Byte Mask This section defines masks for low and high bytes of the STM CCRA\&. 
.SS "#define STM_COMPARE_MATCH_A   1"

.SS "#define STM_COMPARE_MATCH_OUTPUT_MODE   0"

.PP
STM Operating Modes This section defines the operating modes for the STM\&. 
.SS "#define STM_COMPARE_MATCH_P   0"

.PP
STM Comparator Clear Condition Selection This section defines the conditions for clearing the STM comparator\&. 
.SS "#define STM_COUNTER   \fBSTM_COUNTER_ON\fP"

.SS "#define STM_COUNTER_OFF   0"

.PP
STM Counter On/Off Control This section defines the control for turning the STM counter on or off\&. 
.SS "#define STM_COUNTER_ON   1"

.SS "#define STM_DUTY   1"

.PP
STM PWM Duty/Period Control This section defines the duty and period control for the PWM\&. 
.SS "#define STM_INVERT   1"

.SS "#define STM_MODE   \fBSTM_COMPARE_MATCH_OUTPUT_MODE\fP"

.SS "#define STM_NON_INVERT   0"

.PP
STM Output Polarity This section defines the output polarity of the STM\&. 
.SS "#define STM_OUTPUT_MODE   \fBINITIAL_LOW\fP"

.SS "#define STM_OUTPUT_POLARITY   \fBSTM_NON_INVERT\fP"

.SS "#define STM_PERIOD   \fBSTM_1024_CLOCKS\fP"

.SS "#define STM_PERIOD   0"

.SS "#define STM_PIN_FUNCTION   \fBNO_CHANGE\fP"

.SS "#define STM_PWM_DUTY   \fBSTM_DUTY\fP"

.SS "#define STM_PWM_OUTPUT_MODE   3"

.SS "#define STM_SELECT_CLEAR_COMPARE_MATCH   \fBSTM_COMPARE_MATCH_A\fP"

.SS "#define STM_SINGLE_PULSE_OUTPUT_MODE   4"

.SS "#define STM_TIMER_COUNTER_MODE   1"

.SS "#define TOGGLE_OUTPUT   3"

.SH "Function Documentation"
.PP 
.SS "unsigned int readSTimer (void )"

.PP
Reads the current value of the STM timer\&. Reads the current value of the STM timer\&.

.PP
This function reads the current value of the STM timer\&.

.PP
\fBReturns\fP
.RS 4
The current timer value as an unsigned integer\&. 
.RE
.PP

.SS "void STimerInit (void )"

.PP
Function declarations\&. The following functions are declared for initializing and using the STM\&.

.PP
Initializes the STM

.PP
Function declarations\&.

.PP
This function configures the STM counter, clock, mode, and other parameters according to the specified settings\&.

.PP
\fBNote\fP
.RS 4
Ensure to define the required macros (STIMER_CLOCK, STM_PERIOD, etc\&.) before calling this function\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
